root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'prettier/standard'
  - 'standard'
overrides:
  - files:
      - '**/test/**'
      - '**/__tests__/**'
    plugins:
      - 'jest'
    extends:
      - 'plugin:jest/recommended'
      - 'plugin:jest/style'
    env:
      jest: true
